version: '3.7'

volumes:
  logs:
    driver: local

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  api:
    image: php:8-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./server:/var/www
      - ./server/logs:/var/www/logs
